package mx.syncro.melateretro;
import java.io.*; import java.net.*; import java.nio.charset.StandardCharsets; import java.util.*;
public class CsvClient {
 public static final String URL="https://www.loterianacional.gob.mx/Home/Historicos?ARHP=TQBlAGwAYQB0AGUALQBSAGUAdAByAG8A";
 public static List<Draw> fetch() throws Exception {HttpURLConnection c=(HttpURLConnection)new URL(URL).openConnection();c.setConnectTimeout(15000);c.setReadTimeout(25000);c.setRequestProperty("User-Agent","Mozilla/5.0 MelateRetroAnalitica/1.0");int code=c.getResponseCode();if(code<200||code>=300)throw new IOException("HTTP "+code);BufferedReader r=new BufferedReader(new InputStreamReader(c.getInputStream(),StandardCharsets.UTF_8));ArrayList<String> lines=new ArrayList<>();String s;while((s=r.readLine())!=null)lines.add(s);r.close();return parse(lines);}
 public static List<Draw> parse(List<String> lines){ArrayList<Draw> out=new ArrayList<>();if(lines.isEmpty())return out;String[] h=split(lines.get(0));Map<String,Integer>m=new HashMap<>();for(int i=0;i<h.length;i++)m.put(norm(h[i]),i);for(int li=1;li<lines.size();li++){try{String[]p=split(lines.get(li));Integer contest=getInt(p,m,"CONCURSO");String date=getStr(p,m,"FECHA");int[]n=new int[6];boolean ok=true;for(int k=0;k<6;k++){Integer v=getInt(p,m,"F"+(k+1));if(v==null||v<1||v>39){ok=false;break;}n[k]=v;}Integer ad=getInt(p,m,"F7");Long bolsa=getLong(p,m,"BOLSA");if(contest!=null&&ok)out.add(new Draw(contest,date==null?"":date,n,ad==null?0:ad,bolsa==null?0:bolsa));}catch(Exception ignored){}}out.sort((a,b)->Integer.compare(b.contest,a.contest));return out;}
 static String[]split(String s){return s.replace("\uFEFF","").split("[,;\\t]",-1);} static String norm(String s){return s.toUpperCase(Locale.ROOT).replaceAll("[^A-Z0-9]","");}
 static Integer getInt(String[]p,Map<String,Integer>m,String k){String s=getStr(p,m,k);if(s==null)return null;try{return Integer.parseInt(s.replaceAll("[^0-9-]",""));}catch(Exception e){return null;}} static Long getLong(String[]p,Map<String,Integer>m,String k){String s=getStr(p,m,k);if(s==null)return null;try{return Long.parseLong(s.replaceAll("[^0-9-]",""));}catch(Exception e){return null;}} static String getStr(String[]p,Map<String,Integer>m,String k){Integer i=m.get(norm(k));return i!=null&&i<p.length?p[i].trim():null;}
}
