package mx.syncro.melateretro;
import android.app.*;import android.os.*;import android.graphics.*;import android.graphics.drawable.*;import android.util.*;import android.view.*;import android.widget.*;import android.text.*;import java.util.*;
public class MainActivity extends Activity{
 Db db;LinearLayout body;TextView status;List<Draw>draws=new ArrayList<>();Analyzer an;List<Analyzer.Pick>picks=new ArrayList<>();
 int green=Color.rgb(0,105,92),dark=Color.rgb(0,77,64),gold=Color.rgb(255,193,7),ink=Color.rgb(28,31,38),muted=Color.rgb(100,110,125),bg=Color.rgb(242,245,249),border=Color.rgb(224,230,237);
 public void onCreate(Bundle b){super.onCreate(b);db=new Db(this);build();loadLocal();if(draws.isEmpty()){seed();loadLocal();refresh();}}
 int dp(int x){return Math.round(getResources().getDisplayMetrics().density*x);} TextView tv(String s,int sp,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(TypedValue.COMPLEX_UNIT_SP,sp);v.setTextColor(ink);v.setPadding(dp(4),dp(4),dp(4),dp(4));if(bold)v.setTypeface(Typeface.DEFAULT_BOLD);return v;}
 GradientDrawable shape(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
 LinearLayout card(){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(dp(15),dp(15),dp(15),dp(15));GradientDrawable g=shape(Color.WHITE,18);g.setStroke(dp(1),border);x.setBackground(g);x.setElevation(dp(1));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,0,0,dp(12));x.setLayoutParams(lp);return x;}
 Button chip(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(Color.WHITE);b.setTextSize(14);b.setBackground(shape(green,18));b.setPadding(dp(15),dp(7),dp(15),dp(7));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-2,-2);lp.setMargins(0,0,dp(8),0);b.setLayoutParams(lp);return b;}
 Button action(String s,boolean primary){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(primary?Color.WHITE:dark);GradientDrawable g=shape(primary?green:Color.WHITE,14);g.setStroke(dp(1),primary?green:border);b.setBackground(g);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,-2,1);lp.setMargins(0,0,dp(8),0);b.setLayoutParams(lp);return b;}
 void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(16),dp(14),dp(16),dp(10));root.setBackgroundColor(bg);LinearLayout hero=card();hero.setBackground(shape(green,22));TextView t=tv("Melate Retro Analítica",26,true);t.setTextColor(Color.WHITE);hero.addView(t);TextView st=tv("Análisis histórico + combinaciones sugeridas",14,false);st.setTextColor(Color.rgb(224,247,250));hero.addView(st);status=tv("Cargando histórico…",13,false);status.setTextColor(Color.rgb(255,248,225));hero.addView(status);root.addView(hero);HorizontalScrollView hs=new HorizontalScrollView(this);hs.setHorizontalScrollBarEnabled(false);LinearLayout nav=new LinearLayout(this);String[]tabs={"Resumen","Sugerencias","Frecuencias","Pares","Tríos","Historial"};for(String z:tabs){Button b=chip(z);b.setOnClickListener(v->show(z));nav.addView(b);}hs.addView(nav);LinearLayout.LayoutParams hlp=new LinearLayout.LayoutParams(-1,-2);hlp.setMargins(0,0,0,dp(12));root.addView(hs,hlp);LinearLayout ar=new LinearLayout(this);Button up=action("Actualizar datos",true);up.setOnClickListener(v->refresh());Button sg=action("Ver sugerencias",false);sg.setOnClickListener(v->show("Sugerencias"));ar.addView(up);ar.addView(sg);LinearLayout.LayoutParams alp=new LinearLayout.LayoutParams(-1,-2);alp.setMargins(0,0,0,dp(12));root.addView(ar,alp);ScrollView sv=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(0,0,0,dp(50));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}
 void seed(){try{java.io.BufferedReader r=new java.io.BufferedReader(new java.io.InputStreamReader(getAssets().open("melate_retro_seed.csv"),java.nio.charset.StandardCharsets.UTF_8));ArrayList<String>ls=new ArrayList<>();String z;while((z=r.readLine())!=null)ls.add(z);r.close();List<Draw>d=CsvClient.parse(ls);if(!d.isEmpty())db.replaceAll(d);}catch(Exception ignored){}}
 void loadLocal(){draws=db.all();if(!draws.isEmpty()){an=new Analyzer(draws);picks=an.generate(10);status.setText(draws.size()+" sorteos · último #"+draws.get(0).contest+" · "+draws.get(0).date);show("Resumen");}}
 void refresh(){status.setText("Descargando CSV oficial…");new Thread(()->{try{List<Draw>d=CsvClient.fetch();if(d.isEmpty())throw new Exception("sin datos");db.replaceAll(d);runOnUiThread(()->{loadLocal();Toast.makeText(this,"Histórico actualizado",Toast.LENGTH_SHORT).show();});}catch(Exception e){runOnUiThread(()->{status.setText("Sin conexión; usando histórico guardado");if(!draws.isEmpty())show("Resumen");});}}).start();}
 void show(String tab){if(an==null)return;body.removeAllViews();switch(tab){case"Sugerencias":suggestions();break;case"Frecuencias":freq();break;case"Pares":pairs();break;case"Tríos":trios();break;case"Historial":history();break;default:summary();}}
 void title(String a,String b){LinearLayout c=card();TextView x=tv(a,21,true);x.setTextColor(dark);c.addView(x);if(b!=null){TextView y=tv(b,14,false);y.setTextColor(muted);c.addView(y);}body.addView(c);} void metric(String a,String b){LinearLayout c=card();TextView x=tv(a,13,false);x.setTextColor(muted);c.addView(x);TextView y=tv(b,23,true);y.setTextColor(dark);c.addView(y);body.addView(c);} void listCard(String h,List<String>ls){LinearLayout c=card();TextView x=tv(h,18,true);x.setTextColor(dark);c.addView(x);for(String s:ls)c.addView(tv("• "+s,15,false));body.addView(c);}
 void summary(){Draw d=draws.get(0);title("Resumen ejecutivo","Tus sugerencias aparecen aquí y también en la pestaña Sugerencias.");metric("Último sorteo","#"+d.contest+" · "+d.date);metric("Ganadora",d.numbers()+" + "+String.format(Locale.US,"%02d",d.additional));metric("Sorteos analizados",String.valueOf(draws.size()));ArrayList<String>nums=new ArrayList<>();int i=0;for(Analyzer.Stat s:an.numbers()){nums.add(s.key+" · "+s.count+" apariciones · índice "+String.format(Locale.US,"%.2f",s.score));if(++i==8)break;}listCard("Números más fuertes",nums);ArrayList<String>ps=new ArrayList<>();i=0;for(Analyzer.Pick p:picks){ps.add(p.nums()+" · puntaje "+String.format(Locale.US,"%.2f",p.score));if(++i==5)break;}listCard("Top 5 combinaciones sugeridas",ps);listCard("Base del análisis",Arrays.asList("Frecuencia histórica, últimas 100 y últimas 30 tiradas","Pares y tríos dominantes","Paridad, suma, dispersión y repetición reciente","Las sugerencias priorizan patrones; no garantizan un premio"));}
 void suggestions(){title("10 combinaciones sugeridas","Generadas por el motor con frecuencia, recencia, pares, tríos, suma, paridad y dispersión.");int i=0;for(Analyzer.Pick p:picks){LinearLayout c=card();TextView n=tv((++i)+".  "+p.nums(),23,true);n.setTextColor(dark);c.addView(n);TextView sc=tv("Puntaje analítico: "+String.format(Locale.US,"%.2f",p.score),13,true);sc.setTextColor(Color.rgb(70,55,0));sc.setBackground(shape(gold,12));sc.setPadding(dp(10),dp(6),dp(10),dp(6));c.addView(sc);TextView w=tv("Por qué: "+p.why,14,false);w.setTextColor(muted);c.addView(w);body.addView(c);}}
 void freq(){title("Frecuencias ponderadas","Histórico + últimas 100 + últimas 30.");int i=0;for(Analyzer.Stat s:an.numbers()){listCard((++i)+". Número "+s.key,Arrays.asList("Apariciones: "+s.count,"Índice: "+String.format(Locale.US,"%.2f",s.score)));if(i==20)break;}}
 void pairs(){title("Pares dominantes","Los pares con más coincidencias históricas.");int i=0;for(Analyzer.Stat s:an.topPairs()){listCard((++i)+". "+s.key.replace("-"," + "),Collections.singletonList(s.count+" coincidencias"));if(i==20)break;}}
 void trios(){title("Tríos dominantes","Los tríos con más coincidencias históricas.");int i=0;for(Analyzer.Stat s:an.topTrios()){listCard((++i)+". "+s.key.replace("-"," + "),Collections.singletonList(s.count+" coincidencias"));if(i==20)break;}}
 void history(){title("Historial local","Busca concurso, fecha o números.");EditText q=new EditText(this);q.setHint("Ej. 1661 o 12 13");GradientDrawable g=shape(Color.WHITE,15);g.setStroke(dp(1),border);q.setBackground(g);q.setPadding(dp(14),dp(12),dp(14),dp(12));body.addView(q);LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);body.addView(list);Runnable render=()->{list.removeAllViews();String z=q.getText().toString().trim().toLowerCase(Locale.US);int c=0;for(Draw d:draws){String row="#"+d.contest+" · "+d.date+" · "+d.numbers()+" + "+String.format(Locale.US,"%02d",d.additional);if(z.isEmpty()||row.toLowerCase(Locale.US).contains(z)){LinearLayout p=card();p.addView(tv(row,15,false));list.addView(p);if(++c==150)break;}}};q.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int b,int c){}public void onTextChanged(CharSequence s,int a,int b,int c){render.run();}public void afterTextChanged(Editable e){}});render.run();}
}
